# Generated by Django 4.2.8 on 2024-01-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0003_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
